<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [10]:
# it should work for any general input try not to hard code for only given input examples

#function to validate the number is numeric or not. 
def is_valid_number(num):
    if num.isnumeric()==False:
        print("This is not a number!!!. Please enter numbers greater than zero")
        return False
    return True

#function to accept maxtrix size and values and return mXn matrix
def matrix_list():
    # get the matrix size from the user
    row = input("Enter the number of rows to keys in Ex: matrix 2X3 please enter 2\n") 
    col = input("Enter the number of cols to keys in Ex: matrix 2X3 please enter 3\n") 
    
    #if both row and col are valid numbers then proceed, else throw exception and stop
    if is_valid_number(row) and 
            is_valid_number(col) and 
                int(row)>0 and int(col)>0:
        row=int(row)
        col=int(col)

        #initialize the matrix
        matrix=[]
        # loop through rows and cols to get the input from the user
        m=row
        print('enter matrix values in rowise!')
        for i in range(m):
            #initialize row list
            r=[]
            # accept col values for r[] 
            n=col
            for j in range(n):
                c=input()
                if is_valid_number(c):
                    r.append(int(c))
            matrix.append(r) 
    return matrix, row,col


def matrix_mul(A, B):
    #zip and list comprehension used to     
    return [[sum(a * b for a, b in zip(A_row, B_col))  
                            for B_col in zip(*B)] 
                                    for A_row in A] 
    
print("please enter matxix A details")    
matrix_A,rowA,colA =matrix_list()

print("please enter matxix B details")
matrix_B,rowB,colB =matrix_list()

if colA!=rowB:
    print("Martix multiplication can't be done as Columns of Martix A and Rows \
of Matrix don't match")
else:
    matrix_output=matrix_mul(matrix_A,matrix_B)
    print("Matrix A")
    for r in matrix_A:
        print(r)
    print("Matrix B")
    for r in matrix_B:
        print(r)
    
    print("Matrix multiplication of A & B ")
    for r in matrix_output:
        print(r)


please enter matxix A detailsEnter the number of rows to keys in Ex: matrix 2X3 please enter 2
2
Enter the number of cols to keys in Ex: matrix 2X3 please enter 3
3
enter matrix values in rowise!
1
2
3
4
5
6
please enter matxix B detailsEnter the number of rows to keys in Ex: matrix 2X3 please enter 2
3
Enter the number of cols to keys in Ex: matrix 2X3 please enter 3
2
enter matrix values in rowise!
1
4
2
5
3
6
Matrix A
[1, 2, 3]
[4, 5, 6]
Matrix B
[1, 4]
[2, 5]
[3, 6]
Matrix multiplication of A & B 
[14, 32]
[32, 77]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [70]:
from random import uniform
from functools import reduce
from itertools import accumulate

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

A = [0,5,27,6,13,28,100,45,10,79]
#sum = reduce(lambda a,b: int(a)+int(b),A)


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # Step 1: calculate sum using reduce function
    sum=0
    sum = reduce(lambda a,b: int(a)+int(b),A)  
    
    #Step 2: normalize the values using map function
    A_norm=[]
    A_norm=list(map(lambda x: x/sum, A))
    
    #Step 3: find cumulative normalize using accumulate
    A_cum = [*accumulate(A_norm)]
    
    #Step 4. uniform random number
    r = uniform(0.0,1.0)
    number=0
    #step 5. check the random number is lesser than
    # cumulative normalization or not. if matches 
    #return the first occurance and break the loop 
    for p in range(len(A_cum)):
        if(r<=A_cum[p]):
            number=A[p]
            break
    return number

def sampling_based_on_magnitued():
    number=[]
    for i in range(1,100):
        number.append(pick_a_number_from_list(A))
    return number

#driver
r_number_selected=sampling_based_on_magnitued()
print(r_number_selected)

[79, 45, 45, 28, 100, 100, 79, 79, 27, 100, 79, 28, 27, 45, 100, 100, 100, 79, 45, 100, 13, 100, 45, 79, 13, 100, 79, 79, 79, 100, 13, 79, 45, 79, 100, 100, 100, 27, 100, 79, 13, 28, 100, 100, 45, 79, 79, 27, 79, 79, 45, 79, 79, 100, 79, 100, 79, 79, 28, 79, 45, 100, 79, 79, 100, 100, 100, 79, 79, 79, 27, 79, 79, 100, 10, 79, 100, 45, 100, 45, 28, 100, 27, 28, 100, 28, 79, 13, 45, 5, 27, 100, 27, 100, 45, 100, 100, 45, 100]


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [89]:
import re
# String: as input
# the below function removes all wild characters, alphabets
# replaces number with #
# if no number presents, returns empty string
def replace_digits(str):
    result = re.sub(r'[0-9]','#',(re.sub(r'[^0-9]', '', str))) 
    return(result)

#Main 
#input from user
str = input('Please enter the string to remove wildcharacters,alphabets and replace number \
with #')
#invoke replace_digits function to modify the string
modified_str=replace_digits(str)
#if the modified string doesn't have any numbers display this message
if len(modified_str)==0:
    print("The given string doesn't have any numbers to replace with #.")
#else display the modified string 
else:
    print('The given string {} is modified/replaced as {}'.format(str,modified_str))

Please enter the string to remove wildcharacters,alphabets and replace number with ##2a$#b%c%561#
The given string #2a$#b%c%561# is modified/replaced as ####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student6 43
student1 45
student7 47
student5 48
</pre>

In [38]:
import math
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

# to calculate Median, median first half, median second half
# pass the sorted 

def find_median(sorted_list):
    #initialize indices
    indices = []
    #find the size of the list
    total_size = len(sorted_list)
    #initialize median
    median = 0
    #case 1: if the size of the list is even
    if (total_size % 2) == 0:
        #two middles Ex: 1-10 list, 5 and 6 are two middles
        #index starts with 0-9. hence size/2 -1 is first middle index
        #and size/2 is second middle index
        indices.append(math.floor(total_size / 2) - 1)
        indices.append(math.floor(total_size / 2))
        #median is mean of two middle values
        median = (sorted_list[indices[0]] + sorted_list[indices[1]]) / 2

    #case 2: if the the size of the list is odd then middle value is median
    else:
        #Ex: 1-9, 5 is the median
        #To get the index floor(size/2)==> this would return 4 
        #index starts with 0-8 of above list, 4 is middle index
        #hence, list(4) would yield 5 (median) 
        indices.append(math.floor(total_size / 2))
        median = sorted_list[indices[0]]
    #return median and indices list
    return median, indices


def find_IQR(list):
    #IQR defined as  IQR = Q3 – Q1
    # To find Q3 and Q1, first find the center median
    #Step 1: follows
    #Sorted list [12, 14, 35, 43, 45, 47, 48, 78, 80, 98]
    #Median of above the list is (45+47/2)=46
    #To get center median call median function and pass sorted marks list
    #and keep median and median indices
    sorted_list=sorted(list)
    center_median,median_indices = find_median(sorted_list)
    
    #Step 2 follows
    #Q3 = the third quartile (Q3) median of second half values
    #in this example Q3 is between 48 and 98  
    #ie from after center median value(s) till end(inclusive) of sorted list .  
    #To get index of 48 we can use median_index last number +1: [median_indices[-1]+1]
    # call the median function and pass list values from 
    Q3_median,Q3_median_indices = find_median(sorted_list[median_indices[-1]+1 :])
    
    #Step 3 follows
    #Q1 = the first quartile (Q1) median of first half values
    #in this example Q3 is between 12 and 43  
    #ie index from first value till center median value(s) (exclusive).  
    #In this example 12 index=0 and to get 43, we can use median_index: [median_indices[0]]
    # call the median function and pass list values from 
    Q1_median,Q1_median_indices = find_median(sorted_list[:median_indices[0]])
    
    # step 4:
    #IQR = Q3_median-Q1_median
    return (Q3_median-Q1_median) 
    pass
    

def display_dash_board(students, marks):
    #zip Student and Mark records to create dictionary
    stu_dict=dict(zip(Students,Marks))
    
    #sort the student dictionary in ascending order
    stu_dict_sorted ={k: v for k,v in sorted(stu_dict.items(), key=lambda item: item[1])}
    #first 5 records are least scorers
    least_5_students=dict(list(stu_dict_sorted.items())[:5])
    
    #last 5 records from the reverse order are top 5 scorers
    top_5_students=dict(list(stu_dict_sorted.items())[:-6:-1])
    
    #calculate 25th percentile, 75th percentile / Inter Quartile Range [IQR]
    Inter_Quartile_Range=find_IQR(Marks)
    
    #calculate first quartile. If 25th percentile is decimal, then round to higher side. 
    #use math.ceil method to round to higher side
    first_quartile = math.ceil(int(n/4))
    
    #calculate third quartile. if 75th percentile (3/4) is decimal, then rounded to floor side
    # use math.floor method to round to lower side
    third_quartile = math.floor(3*n/4)
  
    #students within 25% and 75% 
    students_within_25_and_75=dict(list(stu_dict_sorted.items())[first_quartile:third_quartile])
    
    return top_5_students, least_5_students, students_within_25_and_75,Inter_Quartile_Range

top_5_students, least_5_students, students_within_25_and_75,IQR = display_dash_board(Students, Marks)

print('Top 5 students : {}'.format(top_5_students))
print('Least 5 students : {}'.format(least_5_students))
print('Students within IQR : {}'.format(students_within_25_and_75))
print('IQR : {}'.format(IQR))


Top 5 students : {'student8': 98, 'student10': 80, 'student2': 78, 'student5': 48, 'student7': 47}
Least 5 students : {'student3': 12, 'student4': 14, 'student9': 35, 'student6': 43, 'student1': 45}
Students within IQR : {'student9': 35, 'student6': 43, 'student1': 45, 'student7': 47, 'student5': 48}
IQR : 54.5


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [76]:
import math

# function to calculate cosine distance between two points
# points from plane x=(x,y) and query point P=(p,q)
# x is tuple x=(x,y)=(x[0],x[1])  
# P is also tuple p=(p,q)=(p[0],[1])

# cosine distance formula = cos-1[(x.p+y.q)/ (SQRT(x**2+y**2).SQRT(p**2+q**2))]
def cosine_distnace(x,p):
    return math.acos(((x[0]*p[0])+(x[1]*p[1]))/
                          ((math.sqrt((x[0]**2)+(x[1]**2)))*(math.sqrt((p[0]**2)+(p[1]**2)))))

#find the n points closest to query point
def closest_points_to_p(S, P, n):
    #Invoke cosine distance function by passing each point and query point
    cosine_dist_lst = [cosine_distnace(i,P) for i in S]
    #merge plane points with cosine distance and create disctionary
    #sort the dictionary based on cosine distanct
    closest_points = sorted(dict(zip(cosine_dist_lst,S)).items())
    #return first n points 
    return closest_points[:n]
    #return closest_points_to_p  # its list of tuples

#Sample plane point
S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]

#Sample query point
P= (3,-4)

# n is number of closest points to query point to be identified
n=5

#call closest_points_to_p function and unzip the distance and points
closest_points_to_p = list(zip(*closest_points_to_p(S, P,n)))

#print points closer to query point
print('These points {} are closer to the query point {}'.format(closest_points_to_p[1:],P))

These points [((6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1))] are closer to the query point (3, -4)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [121]:
import re
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

def mul_dp_lci(p,lci):
    #Example: line: 1x+1y+0 and point(1,1)
    #1*1+1*1+0 = 2
    return ((lci[0]*p[0])+(lci[1]*p[1])+lci[2])

#function to find group of datapoints1 and datapoints2 are seperated or not 
#dp1= datapoints 1[Example: Red]
#dp2 = datapoints 2 [Ex: Blue]
#lci = line coefficient and intercepts 
def are_datapoints_separated(dp1,dp2,lci):
    #invoke data points multiplication with line
    #if the value is +ve then set True else False
    dp1_T_F = list(map(lambda x:(True if x>0 else False),
                                 list([mul_dp_lci(p,lci) for p in dp1])))
    dp2_T_F = list(map(lambda x:(True if x>0 else False),
                                 list([mul_dp_lci(p,lci) for p in dp2])))
    
    #check all datapoints are in one side or not. if so, SET as True 
    #ie all datapoints should be either "True" or "False" but not mixed.
    #all function returns true only if all points are same(True / False)
    dp1_all_in_one =all(element == dp1_T_F[0] for element in dp1_T_F)
    dp2_all_in_one =all(element == dp2_T_F[0] for element in dp2_T_F)
    
    #if both data points True then it is seperated clearly else No
    if (dp1_all_in_one==True and dp2_all_in_one==True):
        return 'Yes'
    else:
        return 'No'

    return 
    
#function to extract coefficients and intercepter from the plane /line
def extract_coeff_intercepter_from_line(lines):
    #Extract line coefficients and intercept using re function
    #It is important to extract coefficient and interceptwith sign to 
    #understand the points are in whcih side
    coeff_str=[re.findall(r'[\d\.\-\+]+', i) for i in Lines]
    #Convert them into float numbers
    coeff =[list(map(lambda x:float(x),x)) for x in coeff_str]
    return coeff

#driver program
#call extract function to seperate coeff and intercepts
coeff=extract_coeff_intercepter_from_line(Lines)

#invoke find datapoint side of the plane of given 
line_separates_yes_no = [are_datapoints_separated(Red,Blue,linecoeffintercept) for linecoeffintercept in coeff]

#zip lines and line_separates_yes_no 
l_seperates = zip(Lines,line_separates_yes_no)
for l in l_seperates:
    print('Does Line {} seperate Red and Blue points ?--> {}'.format(l[0],l[1]))


Does Line 1x+1y+0 seperate Red and Blue points ?--> Yes
Does Line 1x-1y+0 seperate Red and Blue points ?--> No
Does Line 1x+0y-3 seperate Red and Blue points ?--> No
Does Line 0x+1y-0.5 seperate Red and Blue points ?--> Yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
    # your code
    return #list of values

S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(# print above values)

<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    # your code
    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(#the above values)

<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(# the above loss)